### ISSUE TITLE
[JOSS] Slots

### ISSUE THREAD

**Issue by Sulstice** [AstraZeneca/kallisto#20]
Forgive me but it's been awhile since I've seen the `__slots__`  argument. I remember some of the numpy folk arguing about it at the last PyData conference. 

In `src/kallisto/atom.py`, Line 52.

```

    __slots__ = ["data", "molecule", "index"]

    def __init__(self, symbol="X", position=(0, 0, 0), charge=0, molecule=None):

        self.data = data = {}

```

Here's what I'm looking at, can you elaborate on your reason for choosing slots, and does it actually make access to your class attributes access that much faster?

**Comment by f3rmion** [comment]
Hi @Sulstice,

I used it to save RAM once someone wants to create objects with thousands of atoms, since default Python uses a ``dict`` to store an object's instance attribute. However, for small classes with known attributes, this could be quite a waste of memory. 

You can try this yourself (I found a nice example [here](https://book.pythontips.com/en/latest/__slots__magic.html)):

**slots.py**
```python
class MyClass(object):
        __slots__ = ['name', 'identifier']
        def __init__(self, name, identifier):
                self.name = name
                self.identifier = identifier

num = 1024*256
x = [MyClass(1,1) for i in range(num)]
```

**noslots.py**
```python
class MyClass(object):
        def __init__(self, name, identifier):
                self.name = name
                self.identifier = identifier

num = 1024*256
x = [MyClass(1,1) for i in range(num)]
```

We can check the memory usage with this [excellent tool](https://github.com/ianozsvald/ipython_memory_usage).

<img width="911" alt="Screenshot 2021-03-13 at 18 04 11" src="https://user-images.githubusercontent.com/46899008/111037919-934f3f00-8426-11eb-80d4-16b94be48b06.png">

The difference between both shows the memory aspect of ``__slots__`` not sure about the speed though.
It seems to be faster, but this is not really a benchmark :)

**Comment by RMeli** [comment]
Might I suggest to change the variable `__slots__` into a `tuple`? This is nitpicking, but according to "Fluent Python" by Luciano Ramalho it better conveys the fact that the `__slots__` definition can't change.

**Comment by f3rmion** [comment]
OK, I changed ``slots`` into a tuple to stress out its immutability.

**Comment by f3rmion** [comment]
I think this can be closed since the main question (why using ``slots``?) has been answered.
