### ISSUE TITLE
[JOSS] Units 

### ISSUE THREAD

**Issue by Sulstice** [AstraZeneca/kallisto#21]
So digging through your units.py - I'm curious about the design position about implementing your own units instead of using one of your packages dependencies - `scipy`? Is Scipy more trustworthy than the 2014 paper more reputable or vice versa? 

**Scipy Implementation**

```
import scipy.constants as constants

newt_grav = constants.gravitational_constant

```
I think that's the code. It might be conflicting for users down the line to have two sets of constants. I usually just import from scipy. 

Here's the link to the docs: https://docs.scipy.org/doc/scipy/reference/constants.html

**Comparison:**

```

6.6740e-11 (Kallisto) | 6.6743e-11 (SciPy) # Gravitational Constant
6.626070040e-34 (Kallisto) | 6.62607015e-34 (Scipy) # Planck Constant

etc..

```

**Comment by f3rmion** [comment]
Hi @Sulstice,

as described in the resource above, SciPy uses CODATA 2018 data, which is an updated CODATA version (``kallisto`` uses the 2014 version). Since SciPy is already a dependency of ``kallisto``, I will adjust the units accordingly, as this will make it easier to keep units up-to-date in the future. Thanks for this advice!

**Comment by Sulstice** [comment]
Awesome! I must have missed that fact, thank you. Might be worth to have some tests comparing both down the line in case something changes and we might miss it.
