### ISSUE TITLE
[JOSS] VDW radii

### ISSUE THREAD

**Issue by Sulstice** [AstraZeneca/kallisto#22]
This seems like a cool feature to have if it was a dict.

```
truhlar = [
    0.65,  # H
    1.00,  # He
]

```
and turn into:
```
truhlar = {
    "H": 0.65
    "He: 1.00
}
```

And you could access it like so: 

```
from kallisto.data.vdw import truhlar
print (truhlar)

```

Maybe if I needed these for any reason down the line. You could also add it in the docs as "if you want these values or to adjust your own. 

**Update**

I just read through more of your `data.py`. This might something be something useful for users: 

**Example Code**

```
class KallistoData(object):

    def _get_truhlar():
      truhlar = {
          "H": 0.65
          "He: 1.00
      }
      return truhlar

    truhlar = property(_get_truhlar)

```
And you could access it like

```
from kallisto import KallistoData

truhlar = KallistoData.truhlar

```

**Comment by f3rmion** [comment]
Hi @Sulstice,

Definitely a good suggestion! I try to tackle this in the next release :)

**Comment by RMeli** [comment]
For VdW radii and other properties from the periodic table, it might be interesting to have a look at [QCElemental](https://github.com/MolSSI/QCElemental). Not sure if you want to introduce an additional dependency, but might slim down `kallisto/data/__init__.py ` as well.

**Comment by f3rmion** [comment]
The values in ``vdw.py`` are only scaling parameters (termed as ``theta_b`` in the [docs](https://app.gitbook.com/@ehjc/s/kallisto/features/vdw)). Van-der-Waals radii are calculated from atomic static polarizabilities as described in the work of [Fedorov et al.](https://arxiv.org/abs/1803.11507), however, I extended their definition by an atomic parameter that has been fitted to atomic radii. So ``kallisto`` radii are dependent on the chemical environment as well as (partly) on the electronic state since the ``kallisto`` polarizabilities are scaled by atomic partial charges.

> For VdW radii and other properties from the periodic table, it might be interesting to have a look at QCElemental. Not sure if you want to introduce an additional dependency, but might slim down kallisto/data/__init__.py as well.

Definitely worth checking out, but normally I want as few dependencies as possible.

**Comment by f3rmion** [comment]
Since there are only scaling parameter (``theta_b``) in ``vdw.py``, I don't think that users are interested in extracting them for something, which makes something like the following code unnecessary. What do you think?

```python
class KallistoData(object):

    def _get_truhlar():
      truhlar = {
          "H": 0.65,
          "He: 1.00,
      }
      return truhlar

    truhlar = property(_get_truhlar)
```

**Comment by Sulstice** [comment]
Yeah definitely, I like the way you changed it now in vdw.py - simplistic -  Down the line, if you have a lot of different parameters then perhaps that method could be morphed into something similar but that's out of scope.
